package it.unibs.fp.codiceFiscale;
import java.util.ArrayList;
import it.unibs.fp.Support.*;


public class UI {

	public ArrayList<Person> people = new ArrayList<Person>();
	public ArrayList<FiscalCode> fcXml = new ArrayList<FiscalCode>(); //arraylist with fiscal code take from XML codiciFiscali.xml
	public ArrayList<FiscalCode> fcGnted = new ArrayList<FiscalCode>(); //arraylist with fiscal code generated by information in the XML inputPersone.xml
	public ArrayList<HomeTown> cities = new ArrayList<HomeTown>();
	
	//method for generate all the fiscal code by data from the XML collect in the arraylist
	public FiscalCode fcGenerator(ArrayList<Person> people) {
		//chack if the people list is null
		if (people.equals(null)) {
			return null;
		}
		//see the person in the list of people
		for (Person person : people) {
			FiscalCode fc = person.getFc();
			//check if the fiscal code is empty or not
			if (fc.equals(null)) {
				fc.setSurname(CodeGenerator.surnameGenerator(person.getSurname()));
				fc.setName(CodeGenerator.nameGenerator(person.getName()));
				fc.setBirthYearDate(CodeGenerator.yearGenerator(person.getBirthDate()));
				fc.setBirthMonthDate(CodeGenerator.monthGenerator(person.getBirthDate()));
				fc.setBirthDayDate(CodeGenerator.dayGenerator(person.getBirthDate(), person.getGender()));
				fc.setBirthCodPlace(person.getBirthPlace().getCode());//TODO
				
				String codeTemp = fc.getSurname() + 
								  fc.getName() + 
								  fc.getBirthYearDate().toString() + 
								  fc.getBirthMonthDate() +
								  fc.getBirthDayDate().toString() + 
								  fc.getBirthCodPlace();
				
				fc.setControlCharacter(CodeGenerator.controlCharacter(codeTemp));
				//set the code attributes that is all the part of the fiscal code togheter
				fc.setCode(codeTemp + fc.getControlCharacter());
			}
		}
		
		return null;
	}
}
