package it.unibs.fp.codiceFiscale;
import java.util.ArrayList;

public class UI {

	public PersonalData info;
	public ArrayList<FiscalCode> fcXml = new ArrayList<FiscalCode>(); //arraylist with fiscal code take from XML codiciFiscali.xml
	public ArrayList<FiscalCode> fcGnted = new ArrayList<FiscalCode>(); //arraylist with fiscal code generated by information in the XML inputPersone.xml
	
	}
