package it.unibs.fp.codiceFiscale;
import java.util.ArrayList;
import it.unibs.fp.Support.*;


public class UI {

	public ArrayList<Person> people = new ArrayList<Person>();
	public ArrayList<FiscalCode> fcXml = new ArrayList<FiscalCode>(); //arraylist with fiscal code take from XML codiciFiscali.xml
	public ArrayList<FiscalCode> fcGnted = new ArrayList<FiscalCode>(); //arraylist with fiscal code generated by information in the XML inputPersone.xml
	
	
	//method for generate all the fiscal code by data from the XML collect in the arraylist
	public FiscalCode fcGenerator(ArrayList<Person> people) {
		//chack if the people list is null
		if (people.equals(null)) {
			return null;
		}
		//see the person in the list of people
		for (Person person : people) {
			FiscalCode fc = person.getFc();
			//check if the fiscal code is empty or not
			if (fc.equals(null)) {
				fc.setSurname(CodeGenerator.surnameGenerator(person.getSurname()));
			}
		}
		
		return null;
	}
}
